#!/bin/sh
# shellcheck disable=SC2016

#? nix code was borrowed from home modules itself

{
  echo "#!/bin/sh"
  echo
  echo "#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK"
  echo
} > ./linux/.config/shell/aliases.sh

nix eval --impure --raw --expr '
  with import <nixpkgs> { };
  lib.concatStringsSep "\n" (
    lib.mapAttrsToList (k: v: "alias ${k}=${lib.escapeShellArg v}") (
      (import ./nix/home/shell/aliases.nix { inherit lib pkgs; flakePath = toString ./nix; }).sharedAliases
    ))
' >> ./linux/.config/shell/aliases.sh

git add ./linux/.config/shell/aliases.sh


# nix eval --impure --raw --expr '
#   with import <nixpkgs> { };
#   lib.concatStringsSep "\n" (
#     lib.mapAttrsToList (k: v: "alias -- ${k}=${lib.escapeShellArg v}") (
#       lib.filterAttrs (k: v: v != null) (
#         (import ./nix/home/shell/aliases.nix { inherit lib pkgs; flakePath = toString ./nix; }).sharedAliases
#       )))
# ' > ./linux/.config/zsh/aliases.sh

# git add ./linux/.config/zsh/aliases.sh
