#!/bin/sh
# shellcheck disable=SC2016

#? extracts git config from nixosConfigurations.ROG14 into cross-platform INI,
#? filtering out store paths and empty sections

mkdir --parents ./linux/.config/git

{
  echo "#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK"
  echo
  nix eval --impure --raw --expr '
    with import <nixpkgs> { };
    let
      raw =
        (builtins.getFlake (toString ./nix))
        .nixosConfigurations.ROG14.config.home-manager.users.ogurez.programs.git.iniContent;

      hasStorePath =
        v:
        if builtins.isAttrs v then
          lib.any hasStorePath (builtins.attrValues v)
        else if builtins.isString v then
          lib.hasPrefix builtins.storeDir v
        else
          false;

      clean = lib.filterAttrs (_k: v: !hasStorePath v && v != { }) raw;
    in
    lib.generators.toGitINI clean
  '
} > ./linux/.config/git/config

git add ./linux/.config/git/config
