#!/bin/sh
# shellcheck disable=SC2016

#? extracts bare package identifiers from nix/shared/lists/*.nix (one per line,
#? with optional "# * apt:-" (drop) / "# * apt:<name>" (rename) trailing markers) into
#? bash var assignments for the legacy (non-nix) ubuntu bootstrap in setup.sh

extract_list() {
  awk '
    {
      line = $0
      sub(/^[ \t]+/, "", line)
      sub(/[ \t]+$/, "", line)
      if (line == "" || line ~ /^#/) next
      if (line == "{" || line == "}" || line == "[" || line == "]" || line ~ /^with pkgs;/ || line ~ /^\{ pkgs/) next
      ident = line
      sub(/[ \t]*#.*/, "", ident)
      if (ident == "") next
      markerPos = index(line, "# *")
      if (markerPos > 0) {
        marker = substr(line, markerPos + 3)
        sub(/^[ \t]*/, "", marker)
        sub(/[ \t]+$/, "", marker)
      } else {
        marker = ""
      }
      if (marker ~ /^apt:-/) next
      if (marker ~ /^apt:/) {
        sub(/^apt:/, "", marker)
        ident = marker
      }
      printf "%s ", ident
    }
  ' "$1" | sed 's/ $//'
}

{
  echo "#!/bin/sh"
  echo
  echo "#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK"
  echo
  echo "soft_envs() {"
  echo "  soft_unix='$(extract_list ./nix/shared/lists/00_essential.nix)'"
  echo "  soft_base='$(extract_list ./nix/shared/lists/01_base.nix)'"
  echo "  soft_add='$(extract_list ./nix/shared/lists/02_add.nix)'"
  echo "  soft_add_ubuntu='nala build-essential software-properties-common'"
  echo "  soft_to_purge='snapd'"
  echo "}"
  echo
} > ./linux/.config/shell/soft-envs.sh

chmod +x ./linux/.config/shell/soft-envs.sh
git add ./linux/.config/shell/soft-envs.sh
