repos:
  - repo: local
    hooks:
      - id: compile-shell-aliases-from-nix
        name: Run My Shell Script
        entry: ./linux/hooks/compile-aliases.sh
        language: script
        pass_filenames: false
      - id: compile-soft-envs-from-nix
        name: Run My Shell Script
        entry: ./linux/hooks/compile-soft-envs.sh
        language: script
        pass_filenames: false
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: "v3.7.0"
    hooks:
      - id: editorconfig-checker
