repos:
  - repo: local
    hooks:
      - id: compile-shell-aliases-from-nix
        name: Run My Shell Script
        entry: ./linux/hooks/compile-aliases.sh
        language: script
        pass_filenames: false
