{ config, ... }:
let
  inherit (config.xdg) cacheHome configHome dataHome;
in
#? nix run nixpkgs#xdg-ninja
{
  home.sessionVariables = {
    CLAUDE_CONFIG_DIR = "${configHome}/claude"; # ? was ~/.claude*
    WINEPREFIX = "${dataHome}/wine"; # ? was ~/.wine

    #! dev shit
    GOPATH = "${dataHome}/go"; # ? was ~/go
    CARGO_HOME = "${dataHome}/cargo"; # ? was ~/.cargo
    #! docker-desktop ignores it https://github.com/docker/roadmap/issues/408
    DOCKER_CONFIG = "${configHome}/docker"; # ? was ~/.docker
    DOTNET_CLI_HOME = "${dataHome}/dotnet"; # ? was ~/.dotnet

    #! cache
    #? ~/.npm, only holds _logs here, also safe to delete
    NPM_CONFIG_CACHE = "${cacheHome}/npm";
    #? ~/.nv, pure cache, safe to just delete instead of moving
    CUDA_CACHE_PATH = "${cacheHome}/nv";
  };

  #? hopeless, upstream refuses to support XDG:
  #? .vscode + .vscode-shared  https://github.com/microsoft/vscode/issues/3884
  #?   both are actually movable via VSCODE_PORTABLE / VSCODE_EXTENSIONS,
  #?   but VSCODE_PORTABLE drags .config/Code along with them
  #? .vscode-server  only via remote.SSH.serverInstallPath on the *client*, per host, no vars

  #? .steam .steampath .steampid  https://github.com/ValveSoftware/steam-for-linux/issues/1890

  #? .mozilla/native-messaging-hosts  the profile moved to .config/mozilla, manifests did not
  #?   https://bugzilla.mozilla.org/show_bug.cgi?id=2005167
  #?   hardcoded in home-manager too (modules/misc/mozilla-messaging-hosts.nix), no option
  #? .thunderbird  https://bugzilla.mozilla.org/show_bug.cgi?id=735285

  #? .gemini  https://github.com/google-gemini/gemini-cli/issues/2815
  #? .parsec .parsec-persistent  closed source

  #? .pki  chromium hardcodes .pki/nssdb, the string sits right in the electron binary
  #?   so any electron app from gui/autostart.nix recreates it a minute into boot,
  #?   steam (CEF) is just one of many, not the first one
  #!   steam alone can be silenced with extraBwrapArgs = [ "--tmpfs /home/$USER/.pki" ],
  #!   but the dir still gets created: bwrap mkdirs the mountpoint into the bind-mounted $HOME
  #?   killed with extraBwrapArgs in modules/gui/games.nix, but the empty dir stays:
  #?   bwrap has to mkdir the mountpoint, and $HOME is bind-mounted, so it lands on the host

  #? .android  ANDROID_USER_HOME does nothing, adb 36.0.1 builds the path from $HOME only
  #?   verified: `HOME=/nonexistent adb start-server` dies on mkdir '$HOME/.android'
  #?   only fix is the xdg-ninja alias `HOME="$XDG_DATA_HOME"/android adb`,
  #?   which leaks the fake $HOME into adb shell / scrcpy / android-utils.sh
  #! no ~/.java entry here on purpose:
  #!   -Djava.util.prefs.userRoot moves the Preferences API only, the font cache stays put
  #!   and _JAVA_OPTIONS is already taken by font antialiasing in modules/desktop/manager/niri.nix
  #?   https://bugs.java.com/bugdatabase/view_bug?bug_id=8290140

  #? not generated by apps, no action needed:
  #? .icons + .local/share/icons  home.pointerCursor writes both, ~/.icons is hardcoded
  #? .themes  stylix.targets.gtk.flatpakSupport (on by default), path is hardcoded
  #?   and is also passed to flatpak as a ro mount, so it cannot be redirected
  #?   no flatpak here yet, kept enabled in case it shows up
  #?   to drop it: stylix.targets.gtk.flatpakSupport.enable = false;
}
