#!/bin/sh

#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK

soft_envs() {
  soft_unix='git curl wget zip unzip gawk procps psmisc sed grep openssh-client iproute2 iputils-ping iputils-tracepath inetutils-telnet inetutils-traceroute whois diffutils findutils netcat-openbsd'
  soft_base='jq pv bat duf gdu fzf btop neovim zoxide ripgrep ncurses-bin'
  soft_add='fd-find eza lsof mosh tmux rsync tree starship fastfetch zsh'
  soft_add_ubuntu='nala build-essential software-properties-common'
  soft_to_purge='snapd'
}

