from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import os
    from pathlib import Path

    from test_driver.driver import AssertionTester, Driver, Machine, VLan, retry
    from test_driver.logger import TerminalLogger
    from test_driver.machine import StartCommand

    __logger_type = TerminalLogger()

    # ! type definitions for test_symbols
    driver = Driver([], [], "", Path(), __logger_type)

    # ? def driver.test_symbols...
    start_all = driver.start_all
    test_script = driver.test_script
    machines = driver.machines
    vlans = driver.vlans
    log = driver.logger
    os = os
    create_machine = driver.create_machine
    subtest = driver.subtest
    run_tests = driver.run_tests
    join_all = driver.join_all
    retry = retry
    serial_stdout_off = driver.serial_stdout_off
    serial_stdout_on = driver.serial_stdout_on
    polling_condition = driver.polling_condition
    t = AssertionTester()
    debug = driver.debug

    # ? generated by test config in runtime
    machine = Machine(Path(), Path(), StartCommand(), __logger_type)
    vlan1 = VLan(1, Path(), __logger_type)

# machine.succeed()
# create_machine()
