#!/usr/bin/env bun

//! generates shell aliases for linux/ubuntu and zsh completions for nix derivation
//! from `export const commands` in nix/.config/scripts/*.ts
//! runs on pre-commit; to apply without committing, from the repo root:
//!   prek run compile-script-aliases-from-ts --all-files
//!   ./nix/hooks/compile-script-aliases.ts
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const isHook = !process.env.OUT_FILE;
const scriptsDir = resolve(process.env.SCRIPTS_DIR ?? 'nix/.config/scripts');
const outFile = resolve(process.env.OUT_FILE ?? 'linux/.config/shell/script-aliases.sh');
const completionsDir = process.env.COMPLETIONS_DIR ? resolve(process.env.COMPLETIONS_DIR) : undefined;
const completersDir = resolve(process.env.COMPLETERS_DIR ?? join(scriptsDir, 'lib/completions'));

//? paths are cwd-relative by default; without this guard a stray run from elsewhere
//? creates an empty tree there and writes empty outputs into it
if (!existsSync(scriptsDir)) {
  console.error(`${scriptsDir} not found, run from the repo root`);
  process.exit(1);
}

//? single quotes are the only sh metacharacter that matters inside '...'
const quote = (s: string) => `'${s.replaceAll("'", "'\\''")}'`;

type CommandDef = { alias?: string; args?: string; extraAliases?: string[] };

//? the body of an args completer is a zsh snippet named by the `args` key itself,
//? lib/completions/<key>.zsh; it gets inlined into the generated case branch
function argCompleterBody(script: string, sub: string, key: string): string[] {
  const path = join(completersDir, `${key}.zsh`);
  try {
    return readFileSync(path, 'utf8').trim().split('\n');
  } catch {
    throw new Error(`${script}: subcommand "${sub}" names args completer "${key}", but ${path} does not exist`);
  }
}

//? one _file per script, covering the script itself plus its aliases; subcommands
//? with an empty alias are fzf re-invocation targets and stay hidden here too
function completionFor(script: string, defs: Record<string, CommandDef>): string | undefined {
  const visible = Object.entries(defs).filter(([, d]) => d.alias);
  if (visible.length === 0) return undefined;

  const allAliases: string[] = [];
  for (const [, d] of visible) {
    if (d.alias) allAliases.push(d.alias);
    if (d.extraAliases) allAliases.push(...d.extraAliases);
  }

  const lines = [
    `#compdef ${[script, ...allAliases].join(' ')}`,
    '',
    '#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK',
    '',
    '#? aliases arrive unexpanded (COMPLETE_ALIASES is unset): rewrite words to the',
    '#? expanded command line so the dispatch below sees a uniform shape',
    'local _expanded=0',
    'case $words[1] in',
  ];
  for (const [sub, d] of visible) {
    const patterns = [d.alias, ...(d.extraAliases ?? [])].filter(Boolean);
    lines.push(`    (${patterns.join('|')}) words=(${script} ${sub} "\${words[@]:1}"); _expanded=1 ;;`);
  }
  lines.push('esac', '(( _expanded )) && (( CURRENT += 1 ))', '');

  lines.push('if (( CURRENT == 2 )); then', `    compadd -- ${visible.map(([s]) => s).join(' ')}`, '    return', 'fi');

  //? subcommands sharing an args completer fold into one case branch
  const byArgs = new Map<string, string[]>();
  for (const [sub, d] of visible) {
    if (!d.args) continue;
    byArgs.set(d.args, [...(byArgs.get(d.args) ?? []), sub]);
  }
  if (byArgs.size > 0) {
    lines.push('', '(( CURRENT == 3 )) || return', '', 'case $words[2] in');
    for (const [key, subs] of byArgs) {
      lines.push(`    (${subs.join('|')})`);
      for (const l of argCompleterBody(script, subs[0], key)) lines.push(`        ${l}`);
      lines.push('        ;;');
    }
    lines.push('esac');
  }

  return lines.join('\n') + '\n';
}

const aliasLines: string[] = [];
const bashLines: string[] = [];
const written: string[] = [];

if (completionsDir) {
  mkdirSync(completionsDir, { recursive: true });
}

for (const entry of readdirSync(scriptsDir).sort()) {
  if (!entry.endsWith('.ts')) continue;

  const mod = await import(join(scriptsDir, entry));
  const commands: unknown = mod.commands;
  if (!commands || typeof commands !== 'object') continue;
  const defs = commands as Record<string, CommandDef>;

  //? the file itself is the command, it is executable and has a shebang
  for (const [sub, def] of Object.entries(defs)) {
    if (!def?.alias) continue;
    aliasLines.push(`alias ${def.alias}=${quote(`${entry} ${sub}`.trim())}`);
  }

  const visibleSubs = Object.entries(defs)
    .filter(([, d]) => d.alias)
    .map(([s]) => s);
  if (visibleSubs.length > 0) bashLines.push(`    complete -W ${quote(visibleSubs.join(' '))} ${entry}`);

  if (completionsDir) {
    const completion = completionFor(entry, defs);
    if (completion) {
      //? compinit maps the #compdef commands onto the file basename, and the
      //? command already carries the .ts, so the file itself needs no extension
      const name = `_${entry.replace(/\.ts$/, '')}`;
      await Bun.write(join(completionsDir, name), completion);
      written.push(name);
    }
  }
}

if (completionsDir) {
  //? a deleted or emptied script must not leave its completion behind
  for (const f of readdirSync(completionsDir)) {
    if (f.startsWith('_') && !written.includes(f)) rmSync(join(completionsDir, f));
  }
}

const body = [
  '#!/bin/sh',
  '',
  '#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK',
  '',
  ...aliasLines,
  '',
  '#? zsh gets real completions from scripts/completions (fpath); this is the',
  '#? fallback for bash on the ubuntu hosts, subcommand names only',
  'if [ -n "$BASH_VERSION" ]; then',
  ...bashLines,
  'fi',
  '',
].join('\n');

mkdirSync(dirname(outFile), { recursive: true });
await Bun.write(outFile, body);
console.log(`wrote ${aliasLines.length} aliases to ${outFile}`);
if (completionsDir) {
  console.log(`wrote ${written.length} completions to ${completionsDir}`);
}

if (isHook) {
  Bun.spawnSync(['git', 'add', '--force', outFile]);
}
