# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"

    #! lspci -v | grep -iA8 'network\|ethernet'
    "r8169"
    "iwlwifi"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/tank" = {
    device = "tank";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/tank/docker" = {
    device = "tank/docker";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };
  virtualisation.docker.daemon.settings."data-root" = "/tank/docker";

  fileSystems."/tank/apps" = {
    device = "tank/apps";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/tank/storage" = {
    device = "tank/storage";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
