# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    #? https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/scan/not-detected.nix
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5099-6DA0";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/run/media/ogurez/Data" = {
    # device = "/dev/disk/by-uuid/01DC4611808524F0";
    label = "Data";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
    ];
  };
  fileSystems."/run/media/ogurez/System" = {
    # device = "/dev/disk/by-uuid/01DCD272E968DAA0";
    label = "System";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
    ];
  };

  #? https://wiki.nixos.org/wiki/Samba#CIFS_mount_configuration
  fileSystems."/run/media/ogurez/NAS" = {
    # device = "//NAS.lan/storage";
    device = "//192.168.1.2/storage";
    fsType = "cifs";
    options = [
      #? this section prevents hanging on network split
      "_netdev"
      "noauto"
      "x-systemd.automount"
      "x-systemd.device-timeout=5s"
      "x-systemd.mount-timeout=5s"
      "x-systemd.requires=network-online.target"

      #? https://man7.org/linux/man-pages/man8/mount.cifs.8.html
      "soft" # ? disable program locking if mount unaccessible
      "credentials=${config.sops.templates."smb-credentials".path}"
      "rw"
      "uid=1000"
      "gid=100"
      "noserverino"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
