# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/afb30336-18f3-4359-bebb-39c51e8f7b45";
    fsType = "btrfs";
    options = [
      "subvol=@"
    ];
  };
  #? sudo btrfs subvolume create /@nix
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/afb30336-18f3-4359-bebb-39c51e8f7b45";
    fsType = "btrfs";
    # neededForBoot = true;
    options = [
      "subvol=@nix"
      "noatime"
      "compress=zstd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5099-6DA0";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/run/media/ogurez/Data" = {
    # device = "/dev/disk/by-uuid/01DC4611808524F0";
    label = "Data";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
    ];
  };
  fileSystems."/run/media/ogurez/System" = {
    # device = "/dev/disk/by-uuid/01DC45437F7A9E60";
    label = "System";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
    ];
  };
  #? https://wiki.nixos.org/wiki/Samba#CIFS_mount_configuration
  fileSystems."/run/media/ogurez/NAS" = {
    # device = "//admin.lan/storage";
    device = "//192.168.1.4/storage";
    fsType = "cifs";
    options =
      let
        # this line prevents hanging on network split
        automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
      in
      [
        "${automount_opts},credentials=/etc/nixos/smb-secrets"
        "rw"
        "uid=1000"
        "gid=100"

        "noserverino"
      ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
