#!/bin/sh
# shellcheck disable=SC2016

#? nix code was borrowed from home modules itself
# TODO: a lot of hardcode here

{
  echo "#!/bin/sh"
  echo
  echo "#? THIS FILE WAS AUTOGENERATED WITH PRE-COMMIT HOOK"
  echo
} > ./configs/.config/shell/aliases.sh

nix eval --impure --raw --expr '
  with import <nixpkgs> { };
  lib.concatStringsSep "\n" (
    lib.mapAttrsToList (k: v: "alias ${k}=${lib.escapeShellArg v}") (
      (builtins.getFlake (toString ./nix))
      .nixosConfigurations.ROG14.config.home-manager.users.ogurez.programs.bash.shellAliases))
' >> ./configs/.config/shell/aliases.sh

git add ./configs/.config/shell/aliases.sh


# nix eval --impure --raw --expr '
#   with import <nixpkgs> { };
#   lib.concatStringsSep "\n" (
#     lib.mapAttrsToList (k: v: "alias -- ${k}=${lib.escapeShellArg v}") (
#       lib.filterAttrs (k: v: v != null) (
#         (builtins.getFlake "github:barsikus007/config?dir=nix")
#         .nixosConfigurations.ROG14.config.home-manager.users.ogurez.programs.zsh.shellAliases)))
# ' > ./configs/.config/zsh/aliases.sh

# git add ./configs/.config/zsh/aliases.sh
